FROM python:3.12

COPY app.py .

RUN python3 -m pip install flask 

CMD ["python3","app.py"]


#1. ENV DETAILS
#2. DETAILS ABOUT THE MAINTAINER
#3. COPY FILES
#4. DOWNLOAD DEPENDANCES
#5. RUN OUR APPLICATION